package com.example.functional

import com.example.model.ComponentType
import com.example.model.GridComponent
import com.example.engine.EnergyEngine
import com.example.engine.CircuitEngine

/**
 * Definition and helpers for Battery components within the simulator.
 */
object Battery {
    const val DEFAULT_BATTERY_CAPACITY = 2500f
    const val DEFAULT_BATTERY_PACK_CAPACITY = 8000f
    const val DEFAULT_COIN_CELL_CAPACITY = 220f

    /**
     * Checks if a component type is a battery or energy storage.
     */
    fun isBattery(type: ComponentType): Boolean {
        return type == ComponentType.BATTERY ||
               type == ComponentType.BATTERY_PACK ||
               type == ComponentType.COIN_CELL
    }

    /**
     * Retrieves the default maximum capacity of a battery component.
     */
    fun getMaxCapacity(type: ComponentType): Float {
        return when (type) {
            ComponentType.BATTERY -> DEFAULT_BATTERY_CAPACITY
            ComponentType.BATTERY_PACK -> DEFAULT_BATTERY_PACK_CAPACITY
            ComponentType.COIN_CELL -> DEFAULT_COIN_CELL_CAPACITY
            else -> 0f
        }
    }

    /**
     * Gets default voltage generated by the battery.
     */
    fun getDefaultVoltage(type: ComponentType): Float {
        return when (type) {
            ComponentType.BATTERY -> 9f
            ComponentType.BATTERY_PACK -> 12f
            ComponentType.COIN_CELL -> 3f
            else -> 0f
        }
    }
}
