package com.example.functional

import com.example.model.ComponentType
import com.example.engine.CircuitEngine
import com.example.engine.EnergyEngine
import com.example.engine.FluidEngine
import com.example.engine.PhysicsEngine
import com.example.engine.MaterialEngine

/**
 * Definition and helpers for generator components within the simulator.
 */
object Generator {
    /**
     * Checks if a component type is a generator (not a battery).
     */
    fun isGenerator(type: ComponentType): Boolean {
        return type == ComponentType.GENERATOR ||
               type == ComponentType.SOLAR_PANEL ||
               type == ComponentType.AC_SOURCE ||
               type == ComponentType.WIND_TURBINE ||
               type == ComponentType.NUCLEAR_REACTOR ||
               type == ComponentType.GEOTHERMAL_GENERATOR ||
               type == ComponentType.HYDRO_GENERATOR ||
               type == ComponentType.THERMOELECTRIC_GENERATOR
    }

    /**
     * Gets default voltage generated by the generator.
     */
    fun getDefaultVoltage(type: ComponentType): Float {
        return when (type) {
            ComponentType.GENERATOR -> 12f
            ComponentType.SOLAR_PANEL -> 3f
            ComponentType.AC_SOURCE -> 120f
            ComponentType.WIND_TURBINE -> 6f
            ComponentType.NUCLEAR_REACTOR -> 240f
            ComponentType.GEOTHERMAL_GENERATOR -> 24f
            ComponentType.HYDRO_GENERATOR -> 18f
            ComponentType.THERMOELECTRIC_GENERATOR -> 3f
            else -> 0f
        }
    }
}
